name: Build and Release

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            executable_name: BibTeX-Deduplicator.exe
            asset_name: BibTeX-Deduplicator-windows.exe
          - os: macos-latest
            executable_name: BibTeX-Deduplicator
            asset_name: BibTeX-Deduplicator-macos
          - os: ubuntu-latest
            executable_name: BibTeX-Deduplicator
            asset_name: BibTeX-Deduplicator-linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set Windows UTF-8 encoding
      if: runner.os == 'Windows'
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: pip install pyinstaller
    
    - name: Build executable
      run: python build-deduplicator.py
    
    - name: Rename executable for upload
      shell: bash
      run: |
        cd dist
        if [ "${{ runner.os }}" = "Windows" ]; then
          mv BibTeX-Deduplicator.exe ${{ matrix.asset_name }}
        else
          mv BibTeX-Deduplicator ${{ matrix.asset_name }}
        fi
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
    
    - name: Create Release
      uses: ncipollo/create-release@v1
      with:
        artifacts: "artifacts/*/*"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref_name }}
        name: "BibTeX Deduplicator ${{ github.ref_name }}"
        body: |
          ## BibTeX Deduplicator ${{ github.ref_name }}
          
          Cross-platform executables for BibTeX deduplication.
          
          ### Downloads
          - **Windows**: `BibTeX-Deduplicator-windows.exe`
          - **macOS**: `BibTeX-Deduplicator-macos`
          - **Linux**: `BibTeX-Deduplicator-linux`
          
          ### Usage
          Simply download the appropriate file for your platform and double-click to run!
        draft: false
        prerelease: false