name: Build Executables

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            executable_name: BibTeX-Deduplicator.exe
            artifact_name: BibTeX-Deduplicator-windows.exe
          - os: macos-latest
            executable_name: BibTeX-Deduplicator
            artifact_name: BibTeX-Deduplicator-macos
          - os: ubuntu-latest
            executable_name: BibTeX-Deduplicator
            artifact_name: BibTeX-Deduplicator-linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set Windows UTF-8 encoding
      if: runner.os == 'Windows'
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: pip install pyinstaller
    
    - name: Build executable
      run: python build-deduplicator.py
    
    - name: Upload executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: dist/${{ matrix.executable_name }}
        retention-days: 90

  # Job to collect all artifacts and commit to repo
  commit-executables:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create dist directory
      run: mkdir -p dist
    
    - name: Download Windows executable
      uses: actions/download-artifact@v4
      with:
        name: BibTeX-Deduplicator-windows.exe
        path: dist/
    
    - name: Download macOS executable
      uses: actions/download-artifact@v4
      with:
        name: BibTeX-Deduplicator-macos
        path: dist/
    
    - name: Download Linux executable
      uses: actions/download-artifact@v4
      with:
        name: BibTeX-Deduplicator-linux
        path: dist/
    
    - name: Rename executables
      run: |
        mv dist/BibTeX-Deduplicator.exe dist/BibTeX-Deduplicator-windows.exe
        mv dist/BibTeX-Deduplicator dist/BibTeX-Deduplicator-macos
        cp dist/BibTeX-Deduplicator-macos dist/BibTeX-Deduplicator-linux
    
    - name: Commit executables
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/
        git commit -m "Add built executables for ${{ github.ref_name }}" || exit 0
        git push