name: Build Executables

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            executable_name: BibTeX-Deduplicator.exe
          - os: macos-latest
            executable_name: BibTeX-Deduplicator
          - os: ubuntu-latest
            executable_name: BibTeX-Deduplicator
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set Windows UTF-8 encoding
      if: runner.os == 'Windows'
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: pip install pyinstaller
    
    - name: Build executable
      run: python build-deduplicator.py
    
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: bibtex-deduplicator-${{ matrix.os }}
        path: dist/${{ matrix.executable_name }}
        retention-days: 90