name: Build and Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            executable_name: BibTeX-Deduplicator.exe
            asset_name: BibTeX-Deduplicator-windows.exe
          - os: macos-latest
            executable_name: BibTeX-Deduplicator
            asset_name: BibTeX-Deduplicator-macos
          - os: ubuntu-latest
            executable_name: BibTeX-Deduplicator
            asset_name: BibTeX-Deduplicator-linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Set Windows UTF-8 encoding
      if: runner.os == 'Windows'
      run: |
        echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV
        echo "PYTHONUTF8=1" >> $GITHUB_ENV
    
    - name: Install dependencies
      run: pip install pyinstaller
    
    - name: Build executable
      run: python build-deduplicator.py
    
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.executable_name }}
        name: ${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}